template: Hello, %s!
defaultName: Stranger

person:
  type: allen #com.allen.provider.person.PersonProviderFactory
  name: allen
  age: 25
  sex: 1
  hobby: basketball

database:
  # see how to use please open url==>http://www.dropwizard.io/1.1.4/docs/manual/jdbi.html
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: yangtao
  # the password
  password: yangtao
  # the JDBC URL
  url: jdbc:mysql://10.104.3.26:3306/dzcxdb?useUnicode=true&amp;characterEncoding=utf-8
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s
  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute


